// Generated by CoffeeScript 2.3.2
var Bookshelf, Options, Schema, init;

Bookshelf = require('bookshelf');

Schema = require('../lib/');

init = require('./init');

Options = require('../lib/options');

describe('Options', function() {
  var db;
  this.timeout(3000);
  db = null;
  before(function() {
    return db = init.init();
  });
  return it('applies options from schema', function() {
    var User;
    User = (function() {
      class User extends db.Model {};

      User.prototype.tableName = 'users';

      User.schema([
        Options({
          validation: false
        })
      ]);

      return User;

    }).call(this);
    User.__bookshelf_schema_options.validation.should.be.false;
    return db.Model.__bookshelf_schema_options.validation.should.be.true;
  });
});
